const fs = require('fs');
const path = require('path');
const lp = fs.readFileSync('client/src/pages/LandingPage.tsx', 'utf8');
const h1 = lp.match(/<h1[\s\S]*?>([\s\S]*?)<\/h1>/i);
console.log('=== CURRENT H1 ===');
console.log(h1 ? h1[0].substring(0, 400) : 'NO H1 FOUND');
['client/public/locales/ar/translation.json','client/src/locales/ar.json','public/locales/ar/translation.json'].forEach(p => { try { const c = fs.readFileSync(p, 'utf8').replace(/^\uFEFF/, ''); const d = JSON.parse(c); console.log('FOUND AR at:', p); if (d.hero) console.log('hero:', JSON.stringify(d.hero).substring(0, 400)); } catch (e) {} });
['client/src/components/VideoDemo.tsx', 'client/src/components/landing/VideoDemo.tsx'].forEach(p => { try { const c = fs.readFileSync(p, 'utf8'); console.log('VideoDemo FOUND:', p, 'size:', c.length); } catch (e) { console.log('VideoDemo NOT FOUND:', p); } });
console.log('=== LP CHECKS ===');
console.log('has VideoDemo import:', lp.includes('VideoDemo'));
console.log('has VideoDemo JSX:', lp.includes('<VideoDemo'));
console.log('has Sparkles:', lp.includes('Sparkles'));
console.log('LP length:', lp.length);