import { forwardRef } from 'react';

interface Props {
  result: any;
  linkedinUrl: string;
  language: 'ar' | 'en';
}

const T = {
  ar: {
    report: 'تقرير أكاديمي',
    title: 'تحليل البروفايل العميق',
    subtitle: '15 إطاراً أكاديمياً من Harvard و LBS و Wharton',
    outOf100: 'من 100',
    dimensionsTitle: 'تحليل الأبعاد الثمانية',
    insightsTitle: 'رؤى أكاديمية',
    finding: 'الاكتشاف',
    application: 'التطبيق',
    visionTitle: 'مواءمة رؤية 2030',
    pillars: { thriving_economy: 'اقتصاد مزدهر', vibrant_society: 'مجتمع حيوي', ambitious_nation: 'وطن طموح' },
    quickWinsTitle: 'تعديلات فورية — نفّذها الآن',
    quickWinsSubtitle: 'خطوات محددة بوقت تنفيذ واضح، مرتّبة حسب الأولوية',
    footer: 'تقرير مُعدّ بواسطة وصّل — منصة الذكاء الاصطناعي لتطوير البروفايل المهني للسوق السعودي والخليجي',
    builtOn: 'مبني على 15 إطار أكاديمي',
    dims: { headline: 'العنوان الوظيفي', summary: 'الملخص', experience: 'الخبرات', skills: 'المهارات', education: 'التعليم', recommendations: 'التوصيات', activity: 'النشاط', media: 'الوسائط' },
  },
  en: {
    report: 'ACADEMIC REPORT',
    title: 'Deep Profile Analysis',
    subtitle: '15 academic frameworks from Harvard, LBS, and Wharton',
    outOf100: 'out of 100',
    dimensionsTitle: 'Eight-Dimension Breakdown',
    insightsTitle: 'Academic Insights',
    finding: 'Finding',
    application: 'Application',
    visionTitle: 'Vision 2030 Alignment',
    pillars: { thriving_economy: 'Thriving Economy', vibrant_society: 'Vibrant Society', ambitious_nation: 'Ambitious Nation' },
    quickWinsTitle: 'Quick Wins — Act Now',
    quickWinsSubtitle: 'Specific actions with clear timing, ordered by priority',
    footer: 'Generated by Wassel — AI-powered professional profile platform for Saudi & GCC market',
    builtOn: 'Built on 15 academic frameworks',
    dims: { headline: 'Headline', summary: 'Summary', experience: 'Experience', skills: 'Skills', education: 'Education', recommendations: 'Recommendations', activity: 'Activity', media: 'Media' },
  },
};

const PAGE: React.CSSProperties = {
  width: '794px',
  minHeight: '1123px',
  padding: '50px',
  position: 'relative',
  pageBreakAfter: 'always',
  boxSizing: 'border-box',
};

function colorFor(score: number | null | undefined): string {
  if (score == null) return '#94A3B8';
  if (score >= 75) return '#0F6E56';
  if (score >= 50) return '#BA7517';
  return '#A32D2D';
}

function barColorFor(score: number | null | undefined): string {
  if (score == null) return '#CBD5E1';
  if (score >= 75) return '#1D9E75';
  if (score >= 50) return '#EF9F27';
  return '#E24B4A';
}

function Footer({ pageNum, total, isAR }: { pageNum: number; total: number; isAR: boolean }) {
  return (
    <div style={{
      position: 'absolute', bottom: '20px', insetInlineStart: '50px', insetInlineEnd: '50px',
      display: 'flex', justifyContent: 'space-between',
      fontSize: '10px', color: '#94A3B8',
      borderTop: '1px solid #E2E8F0', paddingTop: '10px',
    }}>
      <span>wasselhub.com</span>
      <span style={{ direction: 'ltr' }}>{pageNum} / {total}</span>
    </div>
  );
}

function SectionHeader({ title, accent }: { title: string; accent: string }) {
  return (
    <div style={{ borderBottom: `2px solid ${accent}`, paddingBottom: '12px', marginBottom: '8px' }}>
      <h2 style={{ fontSize: '22px', fontWeight: 700, color: '#0F172A', margin: 0 }}>{title}</h2>
    </div>
  );
}

export const AnalysisPDFTemplate = forwardRef<HTMLDivElement, Props>(({ result, linkedinUrl, language }, ref) => {
  const isAR = language === 'ar';
  const tx = T[language];

  const overallScore = result?.overall_score ?? result?.score ?? 0;
  const dims = result?.dimensions || {};
  const insights = (result?.academic_insights || []).slice(0, 3);
  const quickWins = (result?.quick_wins || []).slice(0, 6);
  const v2030 = result?.vision_2030_alignment || {};

  return (
    <div ref={ref} dir={isAR ? 'rtl' : 'ltr'} style={{
      width: '794px',
      fontFamily: isAR ? "'Cairo', sans-serif" : "'Inter', sans-serif",
      color: '#0F172A',
      background: '#FFFFFF',
    }}>
      {/* PAGE 1 — COVER */}
      <div style={{
        ...PAGE,
        background: 'linear-gradient(135deg, #FAF8F5 0%, #ECFDFB 60%, #FDF6E4 100%)',
        padding: '60px 50px',
        display: 'flex', flexDirection: 'column',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '2px solid #0A8F84', paddingBottom: '16px', marginBottom: '40px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div style={{ width: '44px', height: '44px', borderRadius: '12px', background: 'linear-gradient(135deg, #0A8F84, #C9922A)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#FFFFFF', fontSize: '20px', fontWeight: 700 }}>و</div>
            <div>
              <p style={{ fontSize: '18px', fontWeight: 700, color: '#0F172A', margin: 0 }}>وصّل</p>
              <p style={{ fontSize: '11px', color: '#64748B', margin: 0 }}>wasselhub.com</p>
            </div>
          </div>
          <p style={{ fontSize: '11px', color: '#64748B' }}>
            {new Date().toLocaleDateString(isAR ? 'ar-SA' : 'en-US', { calendar: 'gregory' as any })}
          </p>
        </div>

        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', textAlign: 'center' }}>
          <p style={{ fontSize: '13px', color: '#C9922A', fontWeight: 600, letterSpacing: '2px', marginBottom: '12px' }}>{tx.report}</p>
          <h1 style={{ fontSize: '42px', fontWeight: 700, color: '#0F172A', margin: '0 0 16px', lineHeight: 1.3 }}>{tx.title}</h1>
          <p style={{ fontSize: '16px', color: '#64748B', margin: '0 0 32px' }}>{tx.subtitle}</p>

          <div style={{ display: 'flex', justifyContent: 'center', margin: '24px 0' }}>
            <svg width="220" height="220" viewBox="0 0 220 220">
              <circle cx="110" cy="110" r="95" fill="none" stroke="#E2E8F0" strokeWidth="14" />
              <circle cx="110" cy="110" r="95" fill="none" stroke="url(#pdfGrad)" strokeWidth="14" strokeLinecap="round" strokeDasharray={`${(overallScore / 100) * 597} 597`} transform="rotate(-90 110 110)" />
              <defs>
                <linearGradient id="pdfGrad" x1="0" x2="1" y1="0" y2="1">
                  <stop offset="0%" stopColor="#0A8F84" />
                  <stop offset="100%" stopColor="#C9922A" />
                </linearGradient>
              </defs>
              <text x="110" y="120" textAnchor="middle" fontSize="64" fontWeight="700" fill="#0F172A" direction="ltr">{overallScore}</text>
              <text x="110" y="148" textAnchor="middle" fontSize="13" fill="#64748B">{tx.outOf100}</text>
            </svg>
          </div>

          <div style={{ background: 'rgba(255,255,255,0.85)', border: '1px solid #E2E8F0', borderRadius: '16px', padding: '20px', maxWidth: '500px', margin: '0 auto' }}>
            <p style={{ fontSize: '12px', color: '#94A3B8', margin: 0, direction: 'ltr', wordBreak: 'break-all' }}>{linkedinUrl}</p>
          </div>

          {result?.headline_verdict && (
            <p style={{ fontSize: '14px', color: '#334155', lineHeight: 1.8, maxWidth: '600px', margin: '32px auto 0', fontStyle: 'italic' }}>
              "{result.headline_verdict}"
            </p>
          )}
        </div>

        <div style={{ borderTop: '1px solid #E2E8F0', paddingTop: '16px', display: 'flex', justifyContent: 'space-between', fontSize: '10px', color: '#94A3B8' }}>
          <span>{tx.builtOn}</span>
          <span>Harvard · LBS · Wharton · Stanford · MIT</span>
        </div>
      </div>

      {/* PAGE 2 — DIMENSIONS */}
      <div style={PAGE}>
        <SectionHeader title={tx.dimensionsTitle} accent="#0A8F84" />
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px 32px', marginTop: '24px' }}>
          {(['headline', 'summary', 'experience', 'skills', 'education', 'recommendations', 'activity', 'media'] as const).map(key => {
            const d = dims[key];
            const score = d?.score ?? null;
            return (
              <div key={key}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                  <span style={{ fontSize: '13px', fontWeight: 600, color: '#0F172A' }}>{tx.dims[key]}</span>
                  <span style={{ fontSize: '14px', fontWeight: 700, color: colorFor(score), direction: 'ltr' }}>{score == null ? '—' : score}</span>
                </div>
                <div style={{ height: '6px', background: '#F1F5F9', borderRadius: '3px', overflow: 'hidden' }}>
                  <div style={{ width: `${score || 0}%`, height: '100%', background: barColorFor(score), borderRadius: '3px' }} />
                </div>
                {d?.verdict && (
                  <p style={{ fontSize: '11px', color: '#64748B', marginTop: '6px', lineHeight: 1.6 }}>{d.verdict}</p>
                )}
              </div>
            );
          })}
        </div>
        <Footer pageNum={2} total={4} isAR={isAR} />
      </div>

      {/* PAGE 3 — INSIGHTS + V2030 */}
      <div style={PAGE}>
        <SectionHeader title={`📚 ${tx.insightsTitle}`} accent="#C9922A" />
        <div style={{ marginTop: '24px' }}>
          {insights.map((ins: any, i: number) => {
            const colors = [
              { bg: '#EEEDFE', border: '#534AB7', text: '#26215C' },
              { bg: '#E1F5EE', border: '#0F6E56', text: '#04342C' },
              { bg: '#FAEEDA', border: '#BA7517', text: '#412402' },
            ][i % 3];
            return (
              <div key={i} style={{
                background: colors.bg,
                borderInlineStart: `4px solid ${colors.border}`,
                padding: '16px 20px',
                borderRadius: isAR ? '12px 0 0 12px' : '0 12px 12px 0',
                marginBottom: '14px',
              }}>
                <div style={{ display: 'flex', gap: '8px', marginBottom: '8px', flexWrap: 'wrap' }}>
                  <span style={{ fontSize: '11px', fontWeight: 700, background: '#FFFFFF', padding: '3px 10px', borderRadius: '6px', color: colors.text }}>
                    {ins.framework || ins.source}
                  </span>
                  {ins.category && <span style={{ fontSize: '11px', color: colors.border }}>{ins.category}</span>}
                </div>
                <p style={{ fontSize: '13px', color: colors.text, margin: '0 0 6px', lineHeight: 1.7 }}>
                  <strong>{tx.finding}:</strong> {ins.finding}
                </p>
                <p style={{ fontSize: '12px', color: colors.border, margin: 0, lineHeight: 1.6 }}>
                  <strong>{tx.application}:</strong> {ins.application}
                </p>
              </div>
            );
          })}
        </div>

        <div style={{ background: 'linear-gradient(135deg, #0F6E56, #085041)', borderRadius: '16px', padding: '24px', color: '#FFFFFF', marginTop: '32px' }}>
          <h3 style={{ fontSize: '16px', fontWeight: 700, color: '#FAC775', margin: '0 0 12px' }}>{tx.visionTitle}</h3>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '10px' }}>
            {(['thriving_economy', 'vibrant_society', 'ambitious_nation'] as const).map(p => (
              <div key={p} style={{ background: 'rgba(255,255,255,0.10)', padding: '12px', borderRadius: '10px' }}>
                <p style={{ fontSize: '11px', color: '#FAC775', fontWeight: 600, margin: '0 0 6px' }}>{tx.pillars[p]}</p>
                <p style={{ fontSize: '12px', color: '#FFFFFF', margin: 0, lineHeight: 1.6 }}>{v2030?.[p]?.note || '—'}</p>
              </div>
            ))}
          </div>
        </div>
        <Footer pageNum={3} total={4} isAR={isAR} />
      </div>

      {/* PAGE 4 — QUICK WINS */}
      <div style={{ ...PAGE, pageBreakAfter: 'auto' }}>
        <SectionHeader title={tx.quickWinsTitle} accent="#C9922A" />
        <p style={{ fontSize: '13px', color: '#64748B', marginBottom: '24px' }}>{tx.quickWinsSubtitle}</p>

        {quickWins.map((win: any, i: number) => {
          const priorityColor = win.priority === 'high' ? '#E24B4A' : win.priority === 'medium' ? '#EF9F27' : '#0A8F84';
          const priorityBg = win.priority === 'high' ? '#FEF2F2' : win.priority === 'medium' ? '#FEF3C7' : '#ECFDF5';
          return (
            <div key={i} style={{
              background: priorityBg,
              borderInlineStart: `4px solid ${priorityColor}`,
              padding: '16px 20px',
              borderRadius: isAR ? '12px 0 0 12px' : '0 12px 12px 0',
              marginBottom: '12px',
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '8px', gap: 12 }}>
                <h4 style={{ fontSize: '14px', fontWeight: 700, color: '#0F172A', margin: 0 }}>{i + 1}. {win.action}</h4>
                <span style={{ fontSize: '11px', fontWeight: 600, color: priorityColor, background: '#FFFFFF', padding: '3px 10px', borderRadius: '999px', whiteSpace: 'nowrap' }}>{win.effort}</span>
              </div>
              <p style={{ fontSize: '12px', color: '#334155', margin: '0 0 6px', lineHeight: 1.6 }}>{win.why}</p>
              {win.example && (
                <div style={{ background: '#FFFFFF', padding: '8px 12px', borderRadius: '6px', marginTop: '8px' }}>
                  <p style={{ fontSize: '11px', color: '#64748B', margin: 0, fontFamily: 'monospace' }}>{win.example}</p>
                </div>
              )}
            </div>
          );
        })}

        <div style={{ marginTop: '40px', padding: '20px', background: 'linear-gradient(135deg, #ECFDFB, #FDF6E4)', border: '1px solid #9FE1CB', borderRadius: '16px', textAlign: 'center' }}>
          <p style={{ fontSize: '12px', color: '#065F58', margin: '0 0 6px', lineHeight: 1.7 }}>{tx.footer}</p>
          <p style={{ fontSize: '10px', color: '#64748B', margin: 0 }}>wasselhub.com · Harvard · LBS · Wharton · Stanford · MIT · McKinsey MENA 2024</p>
        </div>

        <Footer pageNum={4} total={4} isAR={isAR} />
      </div>
    </div>
  );
});

AnalysisPDFTemplate.displayName = 'AnalysisPDFTemplate';
